# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
jobs:
  ubuntu-18-04:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        RUBY_VERSION:
        - "2.6"
        - "2.7"
        - "3.0"
        - "head"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.RUBY_VERSION}}
    - name: Install dependencies
      run: gem install test-unit
    - name: Update git submodules
      run: git submodule update --init --recommend-shallow
    - name: Run tests
      run: rake RUBYSET=ruby sofiles && ruby -I lib test/test_blockapi.rb && ruby -Ilib test/test_frameapi.rb
